CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE "IssueStatus" AS ENUM ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "ContentBlockType" AS ENUM ('ARTICLE', 'QUOTE', 'FACT', 'JOKE', 'CALENDAR', 'EVENT', 'COUPON', 'ADVERTISEMENT');
CREATE TYPE "AdStatus" AS ENUM ('ACTIVE', 'PAUSED', 'ARCHIVED');
CREATE TYPE "AdScope" AS ENUM ('GLOBAL', 'CITY', 'VENUE', 'RESTROOM');
CREATE TYPE "AnalyticsEventType" AS ENUM ('SCAN', 'PAGE_VIEW', 'TIME_ON_PAGE', 'AD_IMPRESSION', 'AD_CLICK', 'COUPON_REDEMPTION');
CREATE TYPE "QrCodeStatus" AS ENUM ('INVENTORY', 'ASSIGNED', 'RETIRED');
CREATE TYPE "StripeSubscriptionStatus" AS ENUM ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED');

CREATE TABLE "Publisher" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "contactEmail" TEXT NOT NULL, "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Publisher_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Distributor" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "contactEmail" TEXT NOT NULL, "commissionRate" DECIMAL(65,30) NOT NULL DEFAULT 0.15, "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Distributor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Advertiser" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "contactEmail" TEXT NOT NULL, "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "portalNote" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Advertiser_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Venue" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "distributorId" TEXT, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "city" TEXT NOT NULL, "state" TEXT NOT NULL, "address" TEXT NOT NULL, "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Venue_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Restroom" ("id" TEXT NOT NULL, "venueId" TEXT NOT NULL, "name" TEXT NOT NULL, "floor" TEXT, "placement" TEXT, "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Restroom_pkey" PRIMARY KEY ("id"));
CREATE TABLE "QrCode" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "venueId" TEXT, "restroomId" TEXT, "code" TEXT NOT NULL, "label" TEXT NOT NULL, "destination" TEXT NOT NULL, "status" "QrCodeStatus" NOT NULL DEFAULT 'INVENTORY', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "QrCode_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "color" TEXT NOT NULL DEFAULT '#ffd400', CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Article" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "categoryId" TEXT, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "excerpt" TEXT NOT NULL, "body" TEXT NOT NULL, "imageUrl" TEXT, "status" "IssueStatus" NOT NULL DEFAULT 'DRAFT', "scheduledAt" TIMESTAMP(3), "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Article_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Issue" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "venueId" TEXT NOT NULL, "restroomId" TEXT, "qrCodeId" TEXT, "title" TEXT NOT NULL, "month" TEXT NOT NULL, "year" INTEGER NOT NULL, "issueNumber" INTEGER NOT NULL, "status" "IssueStatus" NOT NULL DEFAULT 'DRAFT', "scheduledAt" TIMESTAMP(3), "publishedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Issue_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IssueContentBlock" ("id" TEXT NOT NULL, "issueId" TEXT NOT NULL, "articleId" TEXT, "type" "ContentBlockType" NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "imageUrl" TEXT, "layout" JSONB, "sortOrder" INTEGER NOT NULL DEFAULT 0, "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "IssueContentBlock_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Ad" ("id" TEXT NOT NULL, "publisherId" TEXT NOT NULL, "advertiserId" TEXT NOT NULL, "businessName" TEXT NOT NULL, "title" TEXT NOT NULL, "offer" TEXT NOT NULL, "artworkUrl" TEXT, "ctaText" TEXT NOT NULL, "targetUrl" TEXT NOT NULL, "phone" TEXT, "couponCode" TEXT, "status" "AdStatus" NOT NULL DEFAULT 'ACTIVE', "scope" "AdScope" NOT NULL DEFAULT 'GLOBAL', "city" TEXT, "state" TEXT, "venueId" TEXT, "restroomId" TEXT, "monthlyPriceCents" INTEGER NOT NULL DEFAULT 0, "stripePriceId" TEXT, "campaignStartsAt" TIMESTAMP(3), "campaignEndsAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Ad_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IssueAdSlot" ("id" TEXT NOT NULL, "issueId" TEXT NOT NULL, "adId" TEXT NOT NULL, "slotNumber" INTEGER NOT NULL, "source" "AdScope" NOT NULL DEFAULT 'GLOBAL', CONSTRAINT "IssueAdSlot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnalyticsEvent" ("id" TEXT NOT NULL, "publisherId" TEXT, "venueId" TEXT, "restroomId" TEXT, "qrCodeId" TEXT, "issueId" TEXT, "advertiserId" TEXT, "adId" TEXT, "type" "AnalyticsEventType" NOT NULL, "slotNumber" INTEGER, "visitorId" TEXT, "sessionId" TEXT, "durationMs" INTEGER, "path" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AnalyticsEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StripeSubscription" ("id" TEXT NOT NULL, "advertiserId" TEXT NOT NULL, "adId" TEXT, "stripeCustomerId" TEXT NOT NULL, "stripeSubscriptionId" TEXT NOT NULL, "status" "StripeSubscriptionStatus" NOT NULL DEFAULT 'TRIALING', "locations" INTEGER NOT NULL DEFAULT 1, "monthlyAmountCents" INTEGER NOT NULL, "currentPeriodEndsAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StripeSubscription_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CouponCampaign" ("id" TEXT NOT NULL, "advertiserId" TEXT NOT NULL, "name" TEXT NOT NULL, "couponCode" TEXT NOT NULL, "budgetCents" INTEGER NOT NULL DEFAULT 0, "redemptionLimit" INTEGER, "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CouponCampaign_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CommissionReport" ("id" TEXT NOT NULL, "distributorId" TEXT NOT NULL, "month" TEXT NOT NULL, "year" INTEGER NOT NULL, "grossRevenueCents" INTEGER NOT NULL, "commissionCents" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CommissionReport_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Publisher_slug_key" ON "Publisher"("slug");
CREATE UNIQUE INDEX "Distributor_publisherId_slug_key" ON "Distributor"("publisherId", "slug");
CREATE UNIQUE INDEX "Advertiser_publisherId_slug_key" ON "Advertiser"("publisherId", "slug");
CREATE UNIQUE INDEX "Venue_slug_key" ON "Venue"("slug");
CREATE UNIQUE INDEX "QrCode_code_key" ON "QrCode"("code");
CREATE UNIQUE INDEX "Category_publisherId_slug_key" ON "Category"("publisherId", "slug");
CREATE UNIQUE INDEX "Article_publisherId_slug_key" ON "Article"("publisherId", "slug");
CREATE UNIQUE INDEX "IssueAdSlot_issueId_slotNumber_key" ON "IssueAdSlot"("issueId", "slotNumber");

ALTER TABLE "Distributor" ADD CONSTRAINT "Distributor_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Advertiser" ADD CONSTRAINT "Advertiser_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Venue" ADD CONSTRAINT "Venue_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Venue" ADD CONSTRAINT "Venue_distributorId_fkey" FOREIGN KEY ("distributorId") REFERENCES "Distributor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Restroom" ADD CONSTRAINT "Restroom_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QrCode" ADD CONSTRAINT "QrCode_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QrCode" ADD CONSTRAINT "QrCode_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "QrCode" ADD CONSTRAINT "QrCode_restroomId_fkey" FOREIGN KEY ("restroomId") REFERENCES "Restroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Category" ADD CONSTRAINT "Category_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Article" ADD CONSTRAINT "Article_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Article" ADD CONSTRAINT "Article_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Issue" ADD CONSTRAINT "Issue_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Issue" ADD CONSTRAINT "Issue_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Issue" ADD CONSTRAINT "Issue_restroomId_fkey" FOREIGN KEY ("restroomId") REFERENCES "Restroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Issue" ADD CONSTRAINT "Issue_qrCodeId_fkey" FOREIGN KEY ("qrCodeId") REFERENCES "QrCode"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IssueContentBlock" ADD CONSTRAINT "IssueContentBlock_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "Issue"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IssueContentBlock" ADD CONSTRAINT "IssueContentBlock_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "Article"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES "Advertiser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_restroomId_fkey" FOREIGN KEY ("restroomId") REFERENCES "Restroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IssueAdSlot" ADD CONSTRAINT "IssueAdSlot_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "Issue"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IssueAdSlot" ADD CONSTRAINT "IssueAdSlot_adId_fkey" FOREIGN KEY ("adId") REFERENCES "Ad"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_venueId_fkey" FOREIGN KEY ("venueId") REFERENCES "Venue"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_restroomId_fkey" FOREIGN KEY ("restroomId") REFERENCES "Restroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_qrCodeId_fkey" FOREIGN KEY ("qrCodeId") REFERENCES "QrCode"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "Issue"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_adId_fkey" FOREIGN KEY ("adId") REFERENCES "Ad"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "StripeSubscription" ADD CONSTRAINT "StripeSubscription_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES "Advertiser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StripeSubscription" ADD CONSTRAINT "StripeSubscription_adId_fkey" FOREIGN KEY ("adId") REFERENCES "Ad"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CommissionReport" ADD CONSTRAINT "CommissionReport_distributorId_fkey" FOREIGN KEY ("distributorId") REFERENCES "Distributor"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES "Advertiser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CouponCampaign" ADD CONSTRAINT "CouponCampaign_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES "Advertiser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
