import Link from "next/link";
import { advertiserForPortalUser, requireAdvertiserPortalUser } from "@/lib/advertiser-portal";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";
export default async function AiBuyerSuccessPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
 const user=await requireAdvertiserPortalUser(); const advertiser=await advertiserForPortalUser(user); const params=await searchParams; const campaignId=params.campaignId;
 const campaign= advertiser && campaignId ? await prisma.adCampaign.findFirst({where:{id:campaignId,advertiserId:advertiser.id},include:{ad:true,placements:{include:{inventory:{include:{venue:true,qrCode:true}}}}}}) : null;
 return <main className="min-h-screen bg-paper p-8 text-ink"><section className="mx-auto max-w-5xl rounded-2xl border-4 border-ink bg-white p-6 shadow-brutal"><p className="font-black uppercase tracking-[.25em] text-stallRed">Payment received</p><h1 className="font-display text-6xl uppercase">AI Media Buyer Success</h1><p className="mt-2 font-bold">Your paid placements publish automatically into purchased sponsor slots.</p>{campaign?<div className="mt-6 grid gap-3">{campaign.placements.map(p=><article key={p.id} className="rounded-xl border-4 border-ink bg-stallYellow p-4"><h2 className="font-display text-4xl uppercase">{p.inventory.venue.name}</h2><p className="font-bold">Slot {p.inventory.slotNumber} • {p.inventory.month} • {p.inventory.qrCode?.shortUrl || p.inventory.qrCode?.qrSlug || "QR route"}</p></article>)}</div>:<p className="mt-4 rounded-xl bg-stallYellow p-4 font-black uppercase">Stripe is finalizing your placements. Refresh in a moment if they do not appear.</p>}<div className="mt-6 flex flex-wrap gap-3"><Link className="rounded-xl bg-ink px-4 py-3 font-black uppercase text-white" href="/portal/advertiser/published">Published ads</Link><Link className="rounded-xl bg-stallRed px-4 py-3 font-black uppercase text-white" href="/portal/advertiser/analytics">Analytics</Link><Link className="rounded-xl border-4 border-ink px-4 py-3 font-black uppercase" href="/portal/advertiser/ai-buyer">Buy more</Link></div></section></main>;
}
