export const AD_ASPECT_RATIO = 4 / 5;
export const AD_DESKTOP_WIDTH = 1080;
export const AD_DESKTOP_HEIGHT = 1350;
export const AD_FINAL_WIDTH = 1080;
export const AD_FINAL_HEIGHT = 1350;
export const AD_MOBILE_WIDTH = 320;
export const AD_MOBILE_HEIGHT = 400;
export const AD_IMAGE_GENERATION_SIZE = "1024x1024";
export const AD_FORMAT_LABEL = "editorial magazine ad";
