import { prisma } from "@/lib/prisma";
import { restroomLabelSelect } from "@/lib/restroom-schema";

export type ReportingRange = { label: string; start?: Date; end?: Date; key: string };

export function parseReportingRange(input?: string | null, from?: string | null, to?: string | null): ReportingRange {
  const now = new Date();
  const end = to ? new Date(`${to}T23:59:59.999Z`) : now;
  const startOfToday = new Date(now); startOfToday.setHours(0, 0, 0, 0);
  if (input === "today") return { key: "today", label: "Today", start: startOfToday, end };
  if (input === "7d") return { key: "7d", label: "Last 7 days", start: new Date(now.getTime() - 6 * 86400000), end };
  if (input === "this-month") { const start = new Date(now); start.setDate(1); start.setHours(0,0,0,0); return { key: "this-month", label: "This month", start, end }; }
  if (input === "custom" && from) return { key: "custom", label: "Custom range", start: new Date(`${from}T00:00:00.000Z`), end };
  return { key: "30d", label: "Last 30 days", start: new Date(now.getTime() - 29 * 86400000), end };
}

const pct = (num: number, den: number) => den ? Number(((num / den) * 100).toFixed(1)) : 0;
const avg = (values: (number | null)[]) => values.length ? Math.round(values.reduce<number>((s, v) => s + (v || 0), 0) / values.length) : 0;
const eventWhere = (range: ReportingRange, extra: any = {}) => ({ ...extra, createdAt: { ...(range.start ? { gte: range.start } : {}), ...(range.end ? { lte: range.end } : {}) } });
const scanWhere = (range: ReportingRange, extra: any = {}) => ({ ...extra, scannedAt: { ...(range.start ? { gte: range.start } : {}), ...(range.end ? { lte: range.end } : {}) } });
function repeatCount(ids: (string | null)[]) { const counts = new Map<string, number>(); ids.filter(Boolean).forEach((id) => counts.set(id!, (counts.get(id!) || 0) + 1)); return [...counts.values()].filter((count) => count > 1).length; }

export async function getQrReporting(range: ReportingRange, qrId?: string) {
  const qrFilter = qrId ? { qrCodeId: qrId } : {};
  const [qrs, scans, events] = await Promise.all([
    prisma.qrCode.findMany({ where: qrId ? { id: qrId } : { status: { not: "RETIRED" } }, include: { venue: true, restroom: { select: restroomLabelSelect }, assignedDistributor: true }, orderBy: { createdAt: "desc" } }),
    prisma.qrScan.findMany({ where: scanWhere(range, qrFilter), include: { qrCode: { include: { venue: true, restroom: { select: restroomLabelSelect }, assignedDistributor: true } }, venue: true, restroom: { select: restroomLabelSelect } }, orderBy: { scannedAt: "desc" }, take: qrId ? 500 : 1000 }),
    prisma.analyticsEvent.findMany({ where: eventWhere(range, { qrCodeId: qrId ? qrId : { not: null } }), include: { qrCode: { include: { venue: true, restroom: { select: restroomLabelSelect } } }, venue: true, restroom: { select: restroomLabelSelect }, ad: true }, orderBy: { createdAt: "desc" }, take: 5000 })
  ]);
  const now = new Date(); const today = new Date(now); today.setHours(0,0,0,0); const week = new Date(now.getTime() - 6 * 86400000); const month = new Date(now); month.setDate(1); month.setHours(0,0,0,0);
  const [scansToday, scansThisWeek, scansThisMonth] = await Promise.all([prisma.qrScan.count({ where: scanWhere({ key: "today", label: "Today", start: today, end: now }, qrFilter) }), prisma.qrScan.count({ where: scanWhere({ key: "7d", label: "Last 7 days", start: week, end: now }, qrFilter) }), prisma.qrScan.count({ where: scanWhere({ key: "this-month", label: "This month", start: month, end: now }, qrFilter) })]);
  const uniqueVisitors = new Set(scans.map(s => s.visitorId).filter(Boolean)).size;
  const issueViews = events.filter(e => ["PAGE_VIEW", "ISSUE_VIEW"].includes(e.type)).length;
  const adImpressions = events.filter(e => e.type === "AD_IMPRESSION").length;
  const adClicks = events.filter(e => ["AD_CLICK", "COUPON_CLICK", "COUPON_REDEMPTION"].includes(e.type)).length;
  const qrRows = qrs.map(qr => { const qs = scans.filter(s => s.qrCodeId === qr.id); const ev = events.filter(e => e.qrCodeId === qr.id); const clicks = ev.filter(e => ["AD_CLICK", "COUPON_CLICK", "COUPON_REDEMPTION"].includes(e.type)).length; const imps = ev.filter(e => e.type === "AD_IMPRESSION").length; const visitors = new Set(qs.map(s => s.visitorId).filter(Boolean)); return { id: qr.id, name: qr.qrName, code: qr.qrSlug, url: qr.qrUrl, venue: qr.venue?.name || "Unassigned", restroom: qr.restroom?.name || "Venue-wide", template: qr.stickerTemplate, distributor: qr.assignedDistributor?.name || "TBD", status: qr.status, totalScans: qs.length, uniqueVisitors: visitors.size, repeatVisitors: repeatCount(qs.map(s => s.visitorId)), issueViews: ev.filter(e => ["PAGE_VIEW", "ISSUE_VIEW"].includes(e.type)).length, adImpressions: imps, adClicks: clicks, ctr: pct(clicks, imps), lastScannedAt: qs[0]?.scannedAt || qr.lastScanAt, createdAt: qr.createdAt }; });
  function perf(group: "venue" | "restroom") { const map = new Map<string, any>(); for (const s of scans) { const obj = group === "venue" ? s.venue : s.restroom; const id = obj?.id || "unassigned"; const row = map.get(id) || { id, name: obj?.name || (group === "venue" ? "Unassigned" : "No restroom data assigned"), venue: s.venue?.name || "Unassigned", scans: 0, visitorSet: new Set(), adClicks: 0, adImpressions: 0, lastScan: s.scannedAt }; row.scans++; if (s.visitorId) row.visitorSet.add(s.visitorId); if (s.scannedAt > row.lastScan) row.lastScan = s.scannedAt; map.set(id, row); } for (const e of events) { const id = (group === "venue" ? e.venueId : e.restroomId) || "unassigned"; const row = map.get(id); if (row) { if (e.type === "AD_IMPRESSION") row.adImpressions++; if (["AD_CLICK", "COUPON_CLICK", "COUPON_REDEMPTION"].includes(e.type)) row.adClicks++; } } return [...map.values()].map(r => ({ ...r, uniqueVisitors: r.visitorSet.size, ctr: pct(r.adClicks, r.adImpressions), visitorSet: undefined })).sort((a,b)=>b.scans-a.scans); }
  const distributors = new Map<string, any>(); for (const q of qrs) if (q.assignedDistributor) { const row = distributors.get(q.assignedDistributor.id) || { id: q.assignedDistributor.id, name: q.assignedDistributor.name, assignedQrCodes: 0, totalScans: 0, venues: new Set(), restrooms: new Set(), adClicksGenerated: 0, estimatedRevenueAttribution: "TBD" }; row.assignedQrCodes++; const qs = scans.filter(s => s.qrCodeId === q.id); row.totalScans += qs.length; qs.forEach(s => { if (s.venueId) row.venues.add(s.venueId); if (s.restroomId) row.restrooms.add(s.restroomId); }); row.adClicksGenerated += events.filter(e => e.qrCodeId === q.id && ["AD_CLICK", "COUPON_CLICK", "COUPON_REDEMPTION"].includes(e.type)).length; distributors.set(q.assignedDistributor.id, row); }
  const adMap = new Map<string, any>(); events.filter(e => e.adId).forEach(e => { const row = adMap.get(e.adId!) || { id: e.adId, businessName: e.ad?.businessName || "Unknown ad", slot: e.slotNumber || "—", impressions: 0, clicks: 0, qrCodes: new Set(), venues: new Set(), restrooms: new Set() }; if (e.type === "AD_IMPRESSION") row.impressions++; if (["AD_CLICK", "COUPON_CLICK", "COUPON_REDEMPTION"].includes(e.type)) row.clicks++; if (e.qrCode?.qrSlug) row.qrCodes.add(e.qrCode.qrSlug); if (e.venue?.name) row.venues.add(e.venue.name); if (e.restroom?.name) row.restrooms.add(e.restroom.name); adMap.set(e.adId!, row); });
  const funnelCounts = [scans.length, issueViews, adImpressions, adClicks, events.filter(e => e.type === "COUPON_REDEMPTION").length];
  return { range, summary: { activeQrCodes: qrs.filter(q => ["ACTIVE", "DEPLOYED"].includes(q.status)).length, totalScans: scans.length, scansToday, scansThisWeek, scansThisMonth, uniqueVisitors, repeatVisitors: repeatCount(scans.map(s=>s.visitorId)), averageDwellTimeMs: avg(scans.map(s=>s.dwellTimeMs)), issueViews, adImpressions, adClicks, adCtr: pct(adClicks, adImpressions), topPerformingVenue: perf("venue")[0]?.name || null, topPerformingRestroom: perf("restroom")[0]?.name || null, topPerformingAd: [...adMap.values()].sort((a,b)=>b.clicks-a.clicks)[0]?.businessName || null, lastScanTime: scans[0]?.scannedAt || null }, qrPerformance: qrRows, venuePerformance: perf("venue"), restroomPerformance: perf("restroom"), distributorPerformance: [...distributors.values()].map(r => ({ ...r, activeVenues: r.venues.size, activeRestrooms: r.restrooms.size, venues: undefined, restrooms: undefined })), adAttribution: [...adMap.values()].map(r => ({ ...r, ctr: pct(r.clicks, r.impressions), qrCodes: [...r.qrCodes], venues: [...r.venues], restrooms: [...r.restrooms] })), scanLog: scans.slice(0, 100).map(s => ({ timestamp: s.scannedAt, qrCode: s.qrCode.qrSlug, venue: s.venue?.name || "Unassigned", restroom: s.restroom?.name || "Venue-wide", deviceType: s.deviceType || "Unknown", browser: s.browser || "Unknown", operatingSystem: s.operatingSystem || "Unknown", approximateLocation: [s.city, s.state, s.country].filter(Boolean).join(", ") || "Unavailable", sessionId: s.sessionId || "—", visitorId: s.visitorId || "—", issueViewed: events.some(e => e.sessionId === s.sessionId && ["PAGE_VIEW", "ISSUE_VIEW"].includes(e.type)), adsClickedCount: events.filter(e => e.sessionId === s.sessionId && ["AD_CLICK", "COUPON_CLICK", "COUPON_REDEMPTION"].includes(e.type)).length })), funnel: ["QR Scan", "Issue View", "Ad Impression", "Ad Click", "Conversion"].map((step, i) => ({ step, count: funnelCounts[i], rateFromPrevious: i ? pct(funnelCounts[i], funnelCounts[i - 1]) : 100, rateFromScan: pct(funnelCounts[i], funnelCounts[0]) })) };
}
