import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { ScheduleActions } from "./ScheduleActions";
import { JulyEventsImportButton } from "@/components/JulyEventsImportButton";
export const dynamic = "force-dynamic";
export default async function SchedulePage() {
  let issues: any[] = []; let error = "";
  try { issues = await prisma.issue.findMany({ include: { venue: true }, orderBy: [{ scheduledPublishAt: "asc" }, { updatedAt: "desc" }] }); } catch (e) { error = e instanceof Error ? e.message : String(e); }
  return <section><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-7xl uppercase">Schedule</h1><p className="font-bold">Loading schedule data from Neon. If this page reports missing columns, run the issue scheduling migration.</p></div><Link href="/admin/issues" className="rounded-xl bg-stallYellow px-4 py-3 font-black uppercase">Schedule Next Month</Link></div><div className="mt-5"><JulyEventsImportButton /></div>{error ? <div className="mt-6 rounded-2xl border-4 border-red-800 bg-red-100 p-5 font-black">Database/schema error: {error}<br/>Migration required if scheduledPublishAt, isScheduled, isPublished, or isArchived columns are missing.</div> : issues.length === 0 ? <div className="mt-6 rounded-2xl border-4 border-ink bg-white p-5 font-black">Empty state: no issues found. Create or duplicate an issue to schedule next month.</div> : <div className="mt-6 overflow-x-auto rounded-2xl border-4 border-ink bg-white shadow-brutal"><table className="w-full text-left"><thead className="bg-stallYellow"><tr>{["Issue","Venue","Month","Year","Status","Scheduled Publish","Published At","Actions"].map(h=><th key={h} className="p-3 font-black uppercase">{h}</th>)}</tr></thead><tbody>{issues.map(issue => <tr key={issue.id} className="border-t-2 border-ink"><td className="p-3 font-black">{issue.title}</td><td className="p-3">{issue.venue?.name || "Global"}</td><td className="p-3">{issue.month}</td><td className="p-3">{issue.year}</td><td className="p-3">{issue.isArchived ? "ARCHIVED" : issue.isPublished ? "PUBLISHED" : issue.isScheduled ? "SCHEDULED" : issue.status}</td><td className="p-3">{issue.scheduledPublishAt?.toISOString?.() || "—"}</td><td className="p-3">{issue.publishedAt?.toISOString?.() || "—"}</td><td className="p-3"><ScheduleActions issueId={issue.id} /></td></tr>)}</tbody></table></div>}</section>;
}
