import Link from "next/link";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function SchedulePage() {
  let issues: any[] = []; let error = "";
  try { issues = await prisma.issue.findMany({ include: { venue: true }, orderBy: [{ year: "desc" }, { issueNumber: "desc" }] }); } catch (e) { error = e instanceof Error ? e.message : String(e); }
  const active = issues.find(i => i.isPublished && !i.isArchived) || issues.find(i => i.status === "PUBLISHED");
  return <section className="grid gap-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-7xl uppercase">Schedule</h1><p className="font-bold">Loading schedule data is automatic on page load. If scheduling columns are missing, run the issue scheduling migration.</p></div>{active ? <form action={`/api/admin/issues/${active.id}/duplicate-next-month`} method="post"><button className="rounded bg-stallRed px-4 py-3 font-black uppercase text-white">Schedule Next Month</button></form> : null}</div>{error ? <div className="rounded-2xl border-4 border-red-800 bg-red-100 p-5 font-black">Database/schema error. Migration required if columns like scheduledPublishAt are missing: {error}</div> : null}{!error && !issues.length ? <div className="rounded-2xl border-4 border-ink bg-white p-5 font-black">Empty state: no issues exist yet. Create an issue, then return to schedule it.</div> : null}<div className="overflow-x-auto rounded-2xl border-4 border-ink bg-white p-5 shadow-brutal"><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr>{["Issue","Venue","Month","Year","Status","Scheduled Publish","Published At","Actions"].map(h=><th key={h} className="border-b-2 border-ink p-2 font-black uppercase">{h}</th>)}</tr></thead><tbody>{issues.map(issue=><tr key={issue.id} className="odd:bg-paper"><td className="p-2 font-black">{issue.title}</td><td className="p-2">{issue.venue?.name || "Global"}</td><td className="p-2">{issue.month}</td><td className="p-2">{issue.year}</td><td className="p-2">{issue.isArchived ? "ARCHIVED" : issue.isPublished ? "PUBLISHED" : issue.isScheduled ? "SCHEDULED" : issue.status}</td><td className="p-2">{issue.scheduledPublishAt?.toISOString?.() || "—"}</td><td className="p-2">{issue.publishedAt?.toISOString?.() || "—"}</td><td className="flex flex-wrap gap-2 p-2"><Action path={`/api/admin/issues/${issue.id}/publish-now`} label="Publish Now"/><Link className="rounded bg-white px-2 py-1 font-black underline" href={`/admin/issues/${issue.id}/edit`}>Reschedule</Link><Action path={`/api/admin/issues/${issue.id}/cancel-schedule`} label="Cancel Schedule"/><Action path={`/api/admin/issues/${issue.id}/duplicate-next-month`} label="Duplicate To Next Month"/><Action path={`/api/admin/issues/${issue.id}/archive`} label="Archive"/><Link className="rounded bg-stallYellow px-2 py-1 font-black" href={issue.venue?.slug ? `/issue/${issue.venue.slug}?previewIssueId=${issue.id}` : `/issue?previewIssueId=${issue.id}`}>Preview</Link></td></tr>)}</tbody></table></div></section>;
}
function Action({path,label}:{path:string;label:string}){return <form action={path} method="post"><button className="rounded bg-ink px-2 py-1 font-black text-white">{label}</button></form>}
