ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'MISSION';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'HILARIOUSLY_FUNNY';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'FEATURE_ARTICLE';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'EVENT_CALENDAR';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'LOCAL_DEALS';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'TRIVIA';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'INSPIRATIONAL_QUOTES';
ALTER TYPE "ContentBlockType" ADD VALUE IF NOT EXISTS 'WORD_OF_THE_MONTH';
