import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { normalizeQrUrl, qrSvgDataUrl } from "@/lib/qr";
import { getQrReporting, parseReportingRange } from "@/lib/qrReporting";

const fmt = (v: unknown) => v instanceof Date ? v.toLocaleString() : String(v ?? "—");
const countBy = (items: any[], key: string) => Object.entries(items.reduce((a, x) => ({ ...a, [x[key] || "Unknown"]: (a[x[key] || "Unknown"] || 0) + 1 }), {} as Record<string, number>));

export default async function QrDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams?: Promise<Record<string, string | undefined>> }) {
  const { id } = await params;
  const sp = (await searchParams) || {};
  const qr = await prisma.qrCode.findFirst({ where: { OR: [{ id }, { qrSlug: id }, { uuid: id }] }, include: { venue: true, restroom: true, assignedDistributor: true } });
  if (!qr) notFound();
  const range = parseReportingRange(sp.range, sp.from, sp.to);
  const report = await getQrReporting(range, qr.id);
  const encodedUrl = normalizeQrUrl(qr.qrSlug, qr.qrUrl);
  const scans = report.scanLog;
  const byHour = Object.entries(scans.reduce((acc, s: any) => { const h = new Date(s.timestamp).getHours(); acc[h] = (acc[h] || 0) + 1; return acc; }, {} as Record<string, number>));
  const byDay = Object.entries(scans.reduce((acc, s: any) => { const d = new Date(s.timestamp).toLocaleDateString(undefined, { weekday: "short" }); acc[d] = (acc[d] || 0) + 1; return acc; }, {} as Record<string, number>));
  const overTime = Object.entries(scans.reduce((acc, s: any) => { const d = new Date(s.timestamp).toISOString().slice(0, 10); acc[d] = (acc[d] || 0) + 1; return acc; }, {} as Record<string, number>));
  return <section className="grid gap-6"><div><a className="font-black underline" href="/admin/qr">← QR dashboard</a><h1 className="font-display text-6xl uppercase md:text-7xl">{qr.qrName}</h1><p className="font-bold">Detailed QR report for {qr.qrSlug}.</p></div><div className="grid gap-4 lg:grid-cols-[320px_1fr]"><section className="rounded-2xl border-4 border-ink bg-white p-4 shadow-brutal"><img src={qrSvgDataUrl(encodedUrl)} alt={`QR code for ${encodedUrl}`} className="mx-auto h-64 w-64 bg-white"/><p className="mt-3 break-all rounded bg-paper p-3 text-sm font-bold">{encodedUrl}</p><p className="font-black">Venue: {qr.venue?.name || "Unassigned"}</p><p className="font-black">Restroom: {qr.restroom?.name || "Venue-wide"}</p><p className="font-black">Distributor: {qr.assignedDistributor?.name || "TBD"}</p></section><div className="grid gap-3 md:grid-cols-3">{[["Total scans", report.summary.totalScans], ["Unique visitors", report.summary.uniqueVisitors], ["Repeat visitors", report.summary.repeatVisitors], ["Ad impressions", report.summary.adImpressions], ["Ad clicks", report.summary.adClicks], ["Ad CTR", `${report.summary.adCtr}%`]].map(([k,v]) => <div key={k} className="rounded-2xl border-4 border-ink bg-stallYellow p-4 shadow-brutal"><p className="font-black uppercase text-stallRed">{k}</p><p className="font-display text-4xl uppercase">{v}</p></div>)}</div></div><div className="grid gap-4 xl:grid-cols-3"><Mini title="Scans over time" rows={overTime}/><Mini title="Hourly scan heatmap" rows={byHour.map(([h,c]) => [`${h}:00`, c])}/><Mini title="Day-of-week breakdown" rows={byDay}/><Mini title="Device breakdown" rows={countBy(scans, "deviceType")}/><Mini title="Browser breakdown" rows={countBy(scans, "browser")}/><Mini title="Operating system breakdown" rows={countBy(scans, "operatingSystem")}/><Mini title="Referrer/source" rows={[["Direct / tracked source", report.summary.totalScans]]}/><Mini title="CTR by ad" rows={report.adAttribution.map(a => [a.businessName, `${a.ctr}% (${a.clicks}/${a.impressions})`])}/><Mini title="Top clicked ads" rows={report.adAttribution.sort((a,b)=>b.clicks-a.clicks).map(a => [a.businessName, a.clicks])}/></div><Table title="Attribution funnel" rows={report.funnel.map(f => [f.step, f.count, `${f.rateFromPrevious}%`, `${f.rateFromScan}%`])} headers={["Step","Count","Rate from previous","Rate from scan"]}/><Table title="Recent scan log" rows={report.scanLog.map(s => [fmt(s.timestamp), s.qrCode, s.venue, s.restroom, s.deviceType, s.browser, s.operatingSystem, s.approximateLocation, s.sessionId, s.visitorId, s.issueViewed ? "Yes" : "No", s.adsClickedCount])} headers={["Timestamp","QR","Venue","Restroom","Device","Browser","OS","Approx location","Session","Visitor","Issue viewed","Ads clicked"]}/></section>;
}
function Mini({ title, rows }: { title: string; rows: any[][] }) { return <section className="rounded-2xl border-4 border-ink bg-white p-4 shadow-brutal"><h2 className="font-display text-3xl uppercase">{title}</h2>{rows.length ? <div className="mt-2 grid gap-2">{rows.map(r => <p key={r.join(":")} className="flex justify-between rounded bg-paper p-2 font-black"><span>{r[0]}</span><span>{r[1]}</span></p>)}</div> : <p className="font-black">No scans in this date range.</p>}</section>; }
function Table({ title, headers, rows }: { title: string; headers: string[]; rows: any[][] }) { return <section className="overflow-hidden rounded-2xl border-4 border-ink bg-white shadow-brutal"><h2 className="bg-ink p-4 font-display text-4xl uppercase text-white">{title}</h2>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr>{headers.map(h => <th key={h} className="bg-stallYellow p-3 font-black uppercase">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="odd:bg-paper">{row.map((cell, j) => <td key={j} className="p-3 font-bold" >{cell}</td>)}</tr>)}</tbody></table></div> : <p className="p-4 font-black">No scans in this date range.</p>}</section>; }
