"use client";
import { useState } from "react";

type Concept = { id:string; headline:string; offer:string; body:string; cta:string; colorPalette:string[]; imagePrompt:string; suggestedFit:string };
type Rec = { id:string; venueName:string; venueType:string; city:string; state:string; zip?:string; slotNumber:number; audienceSegment:string; locationLabel:string; priceCents:number; qrRoute?:string; issueName?:string; estimatedReach:string; why:string };
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);

export function AiBuyerClient({ advertiserName }: { advertiserName: string }) {
  const [brief,setBrief]=useState({businessName:advertiserName,website:"",logoImageUrl:"",photoUrls:"",industry:"",offer:"",city:"",state:"",zip:"",budget:"500",goal:"",prompt:""});
  const [concepts,setConcepts]=useState<Concept[]>([]); const [concept,setConcept]=useState<Concept|null>(null); const [recs,setRecs]=useState<Rec[]>([]); const [cart,setCart]=useState<Rec[]>([]); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  async function post(url:string, payload:any){ const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok) throw new Error(j.error||"Request failed"); return j; }
  async function generate(){ setBusy("Generating Ads"); setError(""); try{ const j=await post("/api/advertiser/ai-buyer/generate-concepts",{...brief, budget:Number(brief.budget), photoUrls:brief.photoUrls.split(/\n|,/).map(s=>s.trim()).filter(Boolean)}); setConcepts(j.concepts); }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy("");}}
  async function recommend(){ if(!concept){setError("Select an ad concept first."); return;} setBusy("Finding Placements"); setError(""); try{ const j=await post("/api/advertiser/ai-buyer/recommend-inventory",{...brief, budget:Number(brief.budget), concept}); setRecs(j.recommendations); }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy("");}}
  async function checkout(){ if(!cart.length){setError("Add at least one placement before checkout."); return;} if(!concept){setError("Select an ad concept first."); return;} setBusy("Checkout with Stripe"); try{ const j=await post("/api/stripe/checkout",{flow:"ai_buyer", inventoryIds:cart.map(i=>i.id), concept, brief:{...brief,budget:Number(brief.budget)}}); if(j.url) location.href=j.url; else setError("Stripe did not return a checkout URL."); }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy("");}}
  const subtotal=cart.reduce((s,i)=>s+i.priceCents,0);
  return <div className="space-y-8">
    {error && <p className="rounded-xl border-4 border-ink bg-stallRed p-4 font-black uppercase text-white">{error}</p>}
    <section className="rounded-2xl border-4 border-ink bg-white p-6 shadow-brutal"><h2 className="font-display text-5xl uppercase">Tell us what you sell</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[["businessName","Business name *"],["website","Website"],["logoImageUrl","Logo image URL"],["photoUrls","Uploaded/photo URLs"],["industry","Industry"],["offer","Offer"],["city","Target city"],["state","Target state"],["zip","Target ZIP"],["budget","Budget"],["goal","Campaign goal *"],["prompt","Prompt/description *"]].map(([k,l])=><label key={k} className="font-black uppercase">{l}<textarea rows={k==="prompt"||k==="photoUrls"?3:1} className="mt-1 w-full rounded-xl border-4 border-ink bg-paper p-3 font-bold normal-case" value={(brief as any)[k]} onChange={e=>setBrief({...brief,[k]:e.target.value})}/></label>)}</div><button onClick={generate} disabled={!!busy} className="mt-5 rounded-xl bg-stallRed px-6 py-3 font-black uppercase text-white shadow-brutal">Generate Ads</button></section>
    <section className="rounded-2xl border-4 border-ink bg-stallYellow p-6 shadow-brutal"><h2 className="font-display text-5xl uppercase">Choose your ad</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{concepts.map(c=><article key={c.id} className="rounded-xl border-4 border-ink bg-white p-4"><div className="mb-3 flex gap-2">{c.colorPalette.map(x=><span key={x} className="h-8 w-8 rounded-full border-2 border-ink" style={{background:x}}/> )}</div><h3 className="font-display text-4xl uppercase">{c.headline}</h3><p className="font-black text-stallRed">{c.offer}</p><p className="font-bold">{c.body}</p><p className="mt-2 text-sm font-black uppercase">{c.suggestedFit}</p><button onClick={()=>setConcept(c)} className="mt-3 rounded-xl bg-ink px-4 py-2 font-black uppercase text-white">{concept?.id===c.id?"Selected":"Select This Ad"}</button></article>)}</div>{concept&&<button onClick={recommend} className="mt-5 rounded-xl bg-stallRed px-6 py-3 font-black uppercase text-white shadow-brutal">Find Placements</button>}</section>
    <section className="rounded-2xl border-4 border-ink bg-white p-6 shadow-brutal"><h2 className="font-display text-5xl uppercase">Pick your placements</h2>{!recs.length?<p className="mt-3 rounded-xl bg-paper p-4 font-bold">No recommendations yet. Generate ads, select one, then find placements. If nothing matches, broaden the city/state/ZIP or budget.</p>:<div className="mt-4 grid gap-4 md:grid-cols-2">{recs.map(r=><article key={r.id} className="rounded-xl border-4 border-ink bg-paper p-4"><p className="font-black uppercase text-stallRed">{r.city}, {r.state} • {r.venueType}</p><h3 className="font-display text-4xl uppercase">{r.venueName}</h3><p className="font-bold">Slot {r.slotNumber}: {r.locationLabel}</p><p>{r.estimatedReach}</p><p className="text-sm font-bold">Why: {r.why}</p><p className="font-display text-3xl">{money(r.priceCents)}/mo</p><button onClick={()=>setCart(cart.find(i=>i.id===r.id)?cart:[...cart,r])} className="mt-2 rounded-xl bg-stallRed px-4 py-2 font-black uppercase text-white">Add to Cart</button></article>)}</div>}</section>
    <section className="rounded-2xl border-4 border-ink bg-stallYellow p-6 shadow-brutal"><h2 className="font-display text-5xl uppercase">Review and pay</h2>{cart.map(i=><div key={i.id} className="mt-3 flex items-center justify-between rounded-xl border-4 border-ink bg-white p-3 font-bold"><span>{i.venueName} • Slot {i.slotNumber} • {money(i.priceCents)}/mo</span><button onClick={()=>setCart(cart.filter(x=>x.id!==i.id))} className="text-stallRed underline">Remove</button></div>)}<p className="mt-4 font-display text-4xl uppercase">Subtotal {money(subtotal)}</p><p className="font-bold">Campaign dates default to the purchased inventory month.</p><button onClick={checkout} disabled={!!busy} className="mt-4 rounded-xl bg-ink px-6 py-3 font-black uppercase text-white shadow-brutal">{busy || "Checkout with Stripe"}</button></section>
  </div>;
}
