ALTER TABLE "Ad" DROP CONSTRAINT IF EXISTS "Ad_publisherId_fkey";
ALTER TABLE "Ad" DROP CONSTRAINT IF EXISTS "Ad_advertiserId_fkey";
ALTER TABLE "Ad" ALTER COLUMN "publisherId" DROP NOT NULL;
ALTER TABLE "Ad" ALTER COLUMN "advertiserId" DROP NOT NULL;
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_publisherId_fkey" FOREIGN KEY ("publisherId") REFERENCES "Publisher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_advertiserId_fkey" FOREIGN KEY ("advertiserId") REFERENCES "Advertiser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
