"use client";
import { useState } from "react";
import { SPONSOR_PLACEMENTS } from "@/lib/sponsor-placements";

export function DefaultIssueEditor({ issue, ads }: { issue: any; ads: any[] }) {
  const [data, setData] = useState(issue);
  const [message, setMessage] = useState("");
  const scheduled = data.scheduledAt ? new Date(data.scheduledAt) : null;
  const [publishDate, setPublishDate] = useState(scheduled ? scheduled.toISOString().slice(0, 10) : "");
  const [publishTime, setPublishTime] = useState(scheduled ? scheduled.toISOString().slice(11, 16) : "");
  const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC");
  const block = (key: string) => data.contentBlocks.find((b: any) => b.layout?.key === key);
  const updateBlock = (id: string, patch: any) => setData((d: any) => ({ ...d, contentBlocks: d.contentBlocks.map((b: any) => b.id === id ? { ...b, ...patch, layout: { ...(b.layout || {}), ...(patch.layout || {}) } } : b) }));
  async function save(action = "draft") {
    const res = await fetch("/api/admin/default-issue", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...data, action, publishDate, publishTime, timezone, blocks: data.contentBlocks, slots: Object.fromEntries(SPONSOR_PLACEMENTS.map((p) => [p.number, data.adSlots.find((s: any) => s.slotNumber === p.number)?.adId || ""])) }) });
    const json = await res.json();
    setMessage(json.ok ? "Saved default global issue." : json.error || "Save failed");
  }
  const keys = [["mission","Mission / Introduction"],["funny","Funny Article"],["feature","Feature Article"],["restaurant","Restaurant Review"],["events","Events / Calendar"],["deals","Local Deals"],["trivia","Trivia / Did You Know"],["quote","Inspirational Quote"],["community","Word + Community Footer"]];
  return <div className="grid gap-5">
    {message && <div className="rounded-xl border-4 border-ink bg-green-100 p-4 font-black">{message}</div>}
    <div className="flex flex-wrap gap-3"><button onClick={() => save("draft")} className="rounded bg-ink px-4 py-3 font-black uppercase text-white">Save Draft</button><button onClick={() => save("publish")} className="rounded bg-stallRed px-4 py-3 font-black uppercase text-white">Publish Now</button><a href="/issue" target="_blank" className="rounded bg-stallYellow px-4 py-3 font-black uppercase">Preview Public Issue</a></div>
    <section className="grid gap-3 rounded-2xl border-4 border-ink bg-white p-5 shadow-brutal md:grid-cols-4"><Field label="Title" value={data.title} onChange={(title: string) => setData({...data,title})}/><Field label="Subtitle" value={data.subtitle || ""} onChange={(subtitle: string) => setData({...data,subtitle})}/><Field label="Venue / Context Label" value={data.contextLabel || "Default Global Issue"} onChange={(contextLabel: string) => setData({...data,contextLabel})}/><Field label="Issue Month" value={data.month} onChange={(month: string) => setData({...data,month})}/><Field label="Issue Year" value={String(data.year)} onChange={(year: string) => setData({...data,year})}/><label className="grid gap-1 font-black uppercase">Status<select className="rounded border-2 border-ink p-3" value={data.status} onChange={e=>setData({...data,status:e.target.value})}><option>DRAFT</option><option>SCHEDULED</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><Field label="Publish Date" type="date" value={publishDate} onChange={setPublishDate}/><Field label="Publish Time" type="time" value={publishTime} onChange={setPublishTime}/><Field label="Timezone" value={timezone} onChange={setTimezone}/></section>
    <section className="grid gap-4 md:grid-cols-2">{keys.map(([key,label]) => { const b=block(key); return b && <div key={key} className="grid gap-2 rounded-2xl border-4 border-ink bg-white p-4"><h2 className="font-display text-4xl uppercase">{label}</h2><Field label="Headline / Title" value={b.title} onChange={(title:string)=>updateBlock(b.id,{title})}/><textarea className="min-h-40 rounded border-2 border-ink p-3" value={b.body} onChange={e=>updateBlock(b.id,{body:e.target.value})}/>{key==="feature" && <Field label="Subtitle" value={b.layout?.subtitle || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{subtitle:v}})}/>} {key==="restaurant" && <><Field label="Restaurant Name" value={b.layout?.restaurantName || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{restaurantName:v}})}/><Field label="Review Headline" value={b.layout?.reviewHeadline || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{reviewHeadline:v}})}/><Field label="Image Upload / URL" value={b.imageUrl || ""} onChange={(imageUrl:string)=>updateBlock(b.id,{imageUrl, layout:{imageUrl}})}/></>}{key==="events" && <><Field label="Event Title" value={b.layout?.eventTitle || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{eventTitle:v}})}/><Field label="Date" type="date" value={b.layout?.eventDate || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{eventDate:v}})}/><Field label="Time" type="time" value={b.layout?.eventTime || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{eventTime:v}})}/><Field label="Location" value={b.layout?.eventLocation || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{eventLocation:v}})}/><Field label="CTA / URL" value={b.layout?.eventUrl || ""} onChange={(v:string)=>updateBlock(b.id,{layout:{eventUrl:v}})}/></>}</div>})}</section>
    <section className="rounded-2xl border-4 border-ink bg-white p-5 shadow-brutal"><h2 className="font-display text-5xl uppercase">Sponsor Placements</h2><div className="grid gap-3 md:grid-cols-4">{SPONSOR_PLACEMENTS.map(p => <label key={p.number} className="grid gap-1 font-black uppercase">{p.label}<span className="text-xs normal-case">Current: {data.adSlots.find((s:any)=>s.slotNumber===p.number)?.ad?.businessName || "Empty / fallback"}</span><select className="rounded border-2 border-ink p-3" value={data.adSlots.find((s:any)=>s.slotNumber===p.number)?.adId || ""} onChange={e=>setData((d:any)=>({ ...d, adSlots: [...d.adSlots.filter((s:any)=>s.slotNumber!==p.number), ...(e.target.value ? [{ slotNumber:p.number, adId:e.target.value, ad: ads.find(a=>a.id===e.target.value)}] : [])] }))}><option value="">Clear placement</option>{ads.map(ad => <option key={ad.id} value={ad.id}>{ad.businessName} • {ad.title}</option>)}</select></label>)}</div></section>
  </div>;
}
function Field({ label, value, onChange, type="text" }: any) { return <label className="grid gap-1 font-black uppercase">{label}<input type={type} className="rounded border-2 border-ink p-3 font-bold normal-case" value={value || ""} onChange={e=>onChange(e.target.value)}/></label> }
